### ISSUE TITLE
5.bindings  connect to redis

### ISSUE THREAD

**Issue by liangyuanpeng** [dapr/samples#86]
## Expected Behavior

node app connect kafka and do not connect redis

## Actual Behavior

just connect to redis and get error:
``
== DAPR == 2019/10/26 16:28:36 redis: connection to localhost:6379 failed: redispipe.connection.could_not_connect: {address: localhost:6379}, cause: dial tcp [::1]:6379: connect: connection refused
``

## Steps to Reproduce the Problem

Follow document execution
[https://github.com/dapr/samples/tree/master/5.bindings](https://github.com/dapr/samples/tree/master/5.bindings)

**Comment by abhirockzz** [comment]
@liangyuanpeng Can you provide more details, like

- Do you want to use Redis as a binding?
- Which step in https://github.com/dapr/samples/tree/master/5.bindings causes the problem

**Comment by liangyuanpeng** [comment]
@abhirockzz 

1.git clone https://github.com/dapr/samples.git  
2.docker-compose -f ./docker-compose-single-kafka.yml up -d  
3.Run docker ps to see the container running locally: 

```
[root@localhost ~]# docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                     PORTS                                                NAMES
b4e76052250b        wurstmeister/kafka:latest       "start-kafka.sh"         32 minutes ago      Up 32 minutes              0.0.0.0:9092->9092/tcp                               5bindings_kafka_1
f4649fe03416        wurstmeister/zookeeper:latest   "/bin/sh -c '/usr/sb…"   32 minutes ago      Up 32 minutes              22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp   5bindings_zookeeper_1
275d4c93ddd5        postgres:9.6-alpine             "docker-entrypoint.s…"   5 weeks ago         Exited (255) 5 weeks ago   0.0.0.0:5432->5432/tcp                               yunhorn_pqsql
[root@localhost ~]#
```

4.cd nodeapp  
5.npm install  
6.dapr run --app-id bindings-nodeapp --app-port 3000 node app.js  

and start up log
```
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="starting Dapr Runtime -- version 0.1.0 -- commit 4358565-dirty"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="log level set to: info"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="standalone mode configured"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="dapr id: bindings-nodeapp"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="loaded component sample-topic (bindings.kafka)"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="loaded component statestore (state.redis)"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="loaded component messagebus (pubsub.redis)"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="application protocol: http. waiting on port 3000"
== APP == Node App listening on port 3000!
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="application discovered on port 3000"
== DAPR == 2019/10/29 05:11:07 redis: connecting to localhost:6379
== DAPR == 2019/10/29 05:11:07 redis: connection to localhost:6379 failed: redispipe.connection.could_not_connect: {address: localhost:6379}, cause: dial tcp [::1]:6379: connect: connection refused
== DAPR == time="2019-10-29T05:11:07-04:00" level=warning msg="error initializing state store state.redis: redispipe.connection.not_connected: {address: localhost:6379}"
== DAPR == 2019/10/29 05:11:07 redis: connecting to localhost:6379
== DAPR == 2019/10/29 05:11:07 redis: connection to localhost:6379 failed: redispipe.connection.could_not_connect: {address: localhost:6379}, cause: dial tcp [::1]:6379: connect: connection refused
== DAPR == time="2019-10-29T05:11:07-04:00" level=warning msg="error initializing pub sub pubsub.redis: redis streams: error connecting to redis at localhost:6379: dial tcp [::1]:6379: connect: connection refused"
== DAPR == time="2019-10-29T05:11:07-04:00" level=warning msg="failed to init actors: actors: state store must be present to initialize the actor runtime"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="http server is running on port 33109"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="gRPC server is running on port 34143"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="local service entry announced"
== DAPR == time="2019-10-29T05:11:07-04:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 307.685259ms"
```

I wanna use Kafka as a binding, just like doc say

Thanks you for your reply

**Comment by abhirockzz** [comment]
`docker ps` does not report the `redis` container, hence the connection error. Ideally, `dapr init` should have started it - please see https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md#install-dapr-runtime-using-the-cli

**Comment by liangyuanpeng** [comment]
@abhirockzz 
Thank you,I solved this problem now.

But,new problem.

Some wrong happen when i run ``dapr run --app-id bindings-pythonapp python app.py``
```
== DAPR == time="2019-10-31T00:16:02-04:00" level=info msg="starting Dapr Runtime -- version 0.1.0 -- commit 4358565-dirty"
== DAPR == time="2019-10-31T00:16:02-04:00" level=info msg="log level set to: info"
== APP ==   File "app.py", line 17
== APP ==     print(payload, flush=True)
== APP ==                         ^
== APP == SyntaxError: invalid syntax
== DAPR == time="2019-10-31T00:16:02-04:00" level=info msg="standalone mode configured"
== DAPR == time="2019-10-31T00:16:02-04:00" level=info msg="dapr id: bindings-pythonapp"
```

I have change ``flush=True`` to ``flush==True`` ,still wrong happen

```
== DAPR == time="2019-10-31T00:18:59-04:00" level=info msg="http server is running on port 44573"
== DAPR == time="2019-10-31T00:18:59-04:00" level=info msg="gRPC server is running on port 45913"
== DAPR == time="2019-10-31T00:18:59-04:00" level=info msg="local service entry announced"
== DAPR == time="2019-10-31T00:18:59-04:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 15.092068ms"
== APP == Traceback (most recent call last):
== APP ==   File "app.py", line 17, in <module>
== APP ==     print(payload, flush==True)
== APP == NameError: name 'flush' is not defined
```

It would be great if I could solve this problem.

**Comment by liangyuanpeng** [comment]
I jus  delete flush=True and it's working  !
